sudo: required
install: travis_wait 5 mvn install
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sachinathu/prodex .

script:
  - docker run sachinathu/prodex npm run test -- --coverage